name: my28brains_temp
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - matplotlib>=3.5.1
  - pip:
    - git+https://github.com/ninamiolane/geomstats.git@surfaces_w_metric
    - jupyter
    - jupyterlab-code-formatter
    - kaleido
    - numpy
    - pykeops
    - plotly
    - psutil
    - open3d
    - requests
    - rtree
    - scikit-image>=0.19.3
    - torch==2.0.0
    - trimesh
    - -r dev-requirements.txt
    - joblib
    - wandb
