name: my28brains
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - matplotlib>=3.5.1
  - pip:
    - jupyter
    - jupyterlab-code-formatter
    - nibabel>=4.0.0
    - nilearn>=0.9.2
    - numpy>=1.23.0
    - scikit-image>=0.19.3
    - -r dev-requirements.txt
