name: my28brains
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - matplotlib>=3.5.1
  - pip:
    - git+https://github.com/geomstats/geomstats.git
    - jupyter
    - jupyterlab-code-formatter
    - nibabel>=4.0.0
    - nilearn>=0.9.2
    - numpy
    - open3d
    - pykeops
    - rtree
    - scikit-image>=0.19.3
    - torch
    - trimesh
    - -r dev-requirements.txt
