name: my28brains
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - matplotlib>=3.5.1
  #- conda-forge::cxx-compiler
  - anaconda::cudatoolkit
  - pip:
    - jupyter
    - jupyterlab-code-formatter
    - nibabel>=4.0.0
    - nilearn>=0.9.2
    - numpy #==1.19.2
    - open3d #==0.12.0
    - pykeops  #==1.5
    - rtree
    - scikit-image>=0.19.3
    - torch #==1.5
    - trimesh
    - -r dev-requirements.txt
