[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "my28brains"
dynamic = ["version"]
authors = [
    {name = "Adele Myers", email = "adele@ucsb.edu"}
]
readme = "README.md"
description = "Brain Shape Analysis through the Menstrual Cycle"
license = {file = "LICENSE.txt"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]
requires-python = ">= 3.10"
dependencies=[
    "geomstats @ git+https://github.com/geomstats/geomstats.git",
    "joblib",
    "kaleido",
    "matplotlib",
    "nibabel",
    "nilearn",
    "open3d",
    "pykeops",
    "plotly",
    "psutil",
    "requests",
    "rtree",
    "scikit-image",
    "trimesh",
    "wandb"
]

[project.optional-dependencies]
doc = [
    "jupyter",
    "jupyterlab",
    "jupyterlab-code-formatter"
]
lint = [
    "black",
    "black[jupyter]",
    "flake8",
    "flake8-docstrings",
    "Flake8-pyproject",
    "isort",
    "pre-commit"
]
test = [
    "pytest",
    "pytest-cov",
    "jupyter"
]

dev = ["my28brains[test, lint]"]
all = ["my28brains[doc, dev]"]

[project.urls]
homepage="https://github.com/geometric-intelligence/my28brains"
repository="https://github.com/geometric-intelligence/my28brains"

[tool.setuptools.dynamic]
version = {attr = "my28brains.__version__"}

[tool.setuptools.packages.find]
include = [
    "my28brains",
    "my28brains.*"
]

[tool.pytest.ini_options]
addopts = "--capture=no"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip = [".gitignore", ".venv"]

[tool.flake8]
application_import_names = "my28brains"
docstring-convention = "numpy"
import_order_style = "smarkets"
max-line-length = 88
extend-exclude = [".venv"]
extend-ignore = ["E501", "F401", "E203"]
per-file-ignores = [
    "*/__init__.py: F401,F403,D104"
]

[tool.coverage.report]
exclude_lines = ["pragma: not covered", "@overload"]