wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688592267.235715
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 1
      - 5
